> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Title Here


### Subtitle Here

Write a short introduction about Numpy and list the chosen functions. 

- function 1
- function 2
- function 3
- function 4
- function 5

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [20]:
!pip install jovian --upgrade -q

In [21]:
import jovian

In [ ]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..


Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [1]:
import numpy as np

In [ ]:
# List of functions explained 
function1 = np.concatenate()  # (change this)
function2 = np.mean()
function3 = np.sort()
function4 = np.where()
function5 = np.around()

## Function 1 - np.concatenate (change this)

Add some explanation about the function in your own words

In [6]:
# Example 1 - working (change this)
# np.concatenate() joins two or more matrices if they have same shapes along a specified axis. If axis=1 it joins the arrays in columns and if axis=0 it joins matrices in rows
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

np.concatenate((arr1, arr2), axis=0)
# with axis=0 it joins arrays in row wise

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

<!-- # np.concatenate() joins two or more matrices if they have same shapes along a specified axis. If axis=1 it joins the arrays in columns and if axis=0 it joins matrices in rows
  # with axis=0 it joins arrays in row wise
-->

In [7]:
# Example 2 - working
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

np.concatenate((arr1, arr2), axis=1)
# with axis=1 it joins arrays in column wise

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

<!-- # with axis=1 it joins arrays in column wise -->

In [11]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=1)

array([[ 1.,  2.,  5.,  6.,  7.],
       [ 3.,  4.,  8.,  9., 10.]])

<!-- Explanation about example (why it breaks and how to fix it) -->
<!--  With axis=0 it joins the matrices in row wise so these two matrices have different column sizes so it raises an error of not having same dimensions. So I use axis=1 it merges two matrices in column wise because we can add columns as many as we want by ensuring we have same no. of rows.  -->

Some closing comments about when to use this function.

## Function 2 - ???

Add some explanations

In [16]:
# Example 1 - working
import numpy as np  
a = np.array([1, 2,3,4,5])  
b = np.mean(a)  
print(b)


3.0


<!-- Explanation about example -->
<!-- np.mean() function is used to calculate the mean/avg of numpy arrays. -->

In [17]:
# Example 2 - working
import numpy as np  
a = np.array([[6,7], [8,9]])  
b=np.mean(a)  
print(b)  


7.5


<!-- Explanation about example -->
<!-- np.mean() with 2D arrays -->

In [18]:
# Example 3 - breaking (to illustrate when it breaks)
import numpy as np 
a = np.array([[3,7,5],[8,4,3],[2,4,9]]) 
print(np.mean(a))

5.0


<!-- Explanation about example (why it breaks and how to fix it) -->
<!-- np.mean() is used to calculate the mean of lists. the sum of total numbers is 45 and mean calculated is 5 because total numbers are 9. -->

Some closing comments about when to use this function.

In [32]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Function 3 - ???

Add some explanations

In [20]:
# Example 1 - working
import numpy as np
a = np.array([10, 7, 4])
print(np.sort(a))

[ 4  7 10]


<!-- Explanation about example -->
<!-- np.sort() is used to sort the elements ascending or descending. It also sorts the elements alphabetically when sorting alphabets  -->

In [22]:
# Example 2 - working
import numpy as np
a = np.array(["c","a","b","z","x"])
print(np.sort(a))

['a' 'b' 'c' 'x' 'z']


<!-- Explanation about example -->
<!-- it sorts the alphabets as well -->

In [24]:
# Example 3 - breaking (to illustrate when it breaks)
import numpy as np
a = np.array([True, False, True])
print(np.sort(a))

[False  True  True]


<!-- Explanation about example (why it breaks and how to fix it) -->
<!-- It also sorts the boolean array -->

Some closing comments about when to use this function.

In [25]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Function 3 - ???

Add some explanations

In [ ]:
# Example 1 - working
import numpy as np
a = np.array([10, 7, 4])
print(np.sort(a))

<!-- Explanation about example -->
<!-- np.sort() is used to sort the elements ascending or descending. It also sorts the elements alphabetically when sorting alphabets  -->

In [ ]:
# Example 2 - working
import numpy as np
a = np.array(["c","a","b","z","x"])
print(np.sort(a))

<!-- Explanation about example -->
<!-- it sorts the alphabets as well -->

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
import numpy as np
a = np.array([True, False, True])
print(np.sort(a))

<!-- Explanation about example (why it breaks and how to fix it) -->
<!-- It also sorts the boolean array -->

<!-- Some closing comments about when to use this function. -->
<!-- This np.sort() should be used when we want to sort elements in ascending or in descending order -->

In [26]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Function 4 - ???

Add some explanations

In [25]:
# Example 1 - working
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x) 

(array([3, 5, 6]),)


<!-- Explanation about example -->
<!-- np.where() is used to search the element and it returns the index numbers at which element are present -->

In [26]:
# Example 2 - working
import numpy as np

arr = np.array(["a","b","c","a"])

x = np.where(arr == "a")

print(x) 

(array([0, 3]),)


<!-- Explanation about example -->
<!-- It returns the indexes 0 and 3 it means 'a' is at index 0 and 3 -->

In [27]:
# Example 3 - breaking (to illustrate when it breaks)
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x) 

(array([1, 3, 5, 7]),)


<!-- Explanation about example (why it breaks and how to fix it) -->
<!-- This code is finding the indexes of even numbers using np.where() built in function and % modulo -->

Some closing comments about when to use this function.

In [27]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Function 5 - ???

Add some explanations

In [30]:
# Example 1 - working
import numpy as np 
a = np.array([1.0,5.55, 123, 0.567, 25.532]) 
np.around(a) 

array([  1.,   6., 123.,   1.,  26.])

<!-- Explanation about example -->
<!-- This np.around() is used to round the numbers -->

In [31]:
# Example 2 - working
import numpy as np 
a = np.array([1.0,5.55, 123, 0.567, 25.532]) 
np.around(a, decimals = 1) 

array([  1. ,   5.6, 123. ,   0.6,  25.5])

<!-- Explanation about example -->
<!-- It rounds the numbers with decimal=1 -->

In [32]:
# Example 3 - breaking (to illustrate when it breaks)
import numpy as np 
a = np.array([1.0,5.55, 123, 0.567, 25.532]) 
np.around(a, decimals = -1) 

array([  0.,  10., 120.,   0.,  30.])

<!-- Explanation about example (why it breaks and how to fix it) -->
<!-- if decimal=-1 the integer is rounded to position to the left of the decimal point -->

Some closing comments about when to use this function.

In [28]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [30]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'